### ISSUE TITLE
Test files should be ignored by npm artifacts

### ISSUE THREAD

**Issue by fujikky** [jubilee-works/timetree-sdk-js#288]
The test files are included in the published npm artifacts.  These are unnecessary for operation and should be ignored.

https://app.renovatebot.com/package-diff?name=@timetreeapp%2fweb-api&from=1.7.5&to=2.0.0

**Comment by hilott** [comment]
https://qiita.com/mizchi/items/bf2da480b0a7f216ba78

**Comment by hilott** [comment]
修正済みのためクローズします
